version: '3.8'

services:
  nextjs:
    image: ${DOCKER_REGISTRY-}nextjs
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: docker/entrypoint.prod.sh
    ports:
      - '80:80'
      - '8288:8288'
    volumes:
      - .:/appNextJS
    restart: always
